name: Subscribe_free

on:
  schedule:
    - cron: '2 0,6,12,18 * * *'
jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install requests parsel pyperclip
      - name: Update list
        run: |
          # cd paper_infos
          python free.py
