name: Subscribe_free

on:
  push:
    branches:
      - master
  schedule:
    - cron: '2 4,10,16,22 * * *'
jobs:
  csdn-emailbot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set python'
        uses: actions/setup-python@v1
        with:
          python-version: '3.7'
          
      - name: 'Install dependencies'
        run: |
          python -m pip install --upgrade pip
          pip install requests parsel pyperclip
      - name: Update list
        run: |
          # cd paper_infos
          python free.py

      - name: Commit changes
        uses: EndBug/add-and-commit@v5
        with:
          # author_name: Your Name
          # author_email: mail@example.com
          message: "update"
          add: "*.txt"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
